type Task {
  id: ID!
  description: String!
  status: String!
  createdAt: String
  updatedAt: String
  deletedAt: String
}
input TaskInput {
  description: String!
  status: String!
}
type Query {
  getTasks: [Task!]!
  getTask(id: ID!): Task!
}
type Mutation {
  createTask(data: TaskInput!): Task!
  updateTask(id: ID!, data: TaskInput!): Task!
  deleteTask(id: ID!): Task!
}
